#!/usr/bin/env bash
# Interactive local connect — writes gitignored env files. Run once after Supabase project exists.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
API_ENV="$ROOT/api/.env"
WEB_ENV="$ROOT/web/.env.local"

echo "=== TRA Supabase connect ==="
echo "Paste values from Supabase (Settings → API / Database). Input is not echoed for secrets."
echo

read -r -p "Project URL (https://xxxx.supabase.co): " SUPABASE_URL
read -r -p "anon public key: " ANON_KEY
read -r -s -p "JWT Secret: " JWT_SECRET
echo
read -r -s -p "DATABASE_URL (postgres URI): " DATABASE_URL
echo

if [[ -z "$SUPABASE_URL" || -z "$ANON_KEY" || -z "$JWT_SECRET" || -z "$DATABASE_URL" ]]; then
  echo "Error: all four values are required." >&2
  exit 1
fi

# Normalize postgres scheme for clarity (API also normalizes)
# Keep user-supplied URI as-is

cat > "$API_ENV" <<EOF
# Generated by scripts/connect-supabase.sh — gitignored
DATABASE_URL=${DATABASE_URL}
SUPABASE_JWT_SECRET=${JWT_SECRET}
SUPABASE_URL=${SUPABASE_URL}
CORS_ORIGINS=http://localhost:3000,https://totalrewardsaccelerator.com,https://www.totalrewardsaccelerator.com
CORS_ORIGIN_REGEX=https://.*\\.vercel.app
EOF

cat > "$WEB_ENV" <<EOF
# Generated by scripts/connect-supabase.sh — gitignored
NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF

chmod 600 "$API_ENV" "$WEB_ENV"
echo
echo "Wrote:"
echo "  $API_ENV"
echo "  $WEB_ENV"
echo
echo "Next: start API + web (or ask Grok to verify health)."
echo "  cd $ROOT/api && PYTHONPATH=. python3 -m uvicorn app.main:app --reload --port 8000"
echo "  cd $ROOT/web && npm run dev"
echo "  open http://localhost:3000/signup"
