#!/usr/bin/env python3
"""
Create TRA Stripe products + monthly prices, write api/.env.stripe (gitignored).

Usage:
  export STRIPE_SECRET_KEY=sk_test_...   # or sk_live_...
  python3 scripts/setup-stripe-products.py

Then merge .env.stripe into Render env (and local api/.env).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

try:
    import stripe
except ImportError:
    print("Install stripe: python3 -m pip install stripe")
    sys.exit(1)

# Mid-range of published pricing bands (USD / month)
PRODUCTS = [
    {
        "key": "cleaner",
        "name": "TRA Cleaner",
        "description": "Market Data Cleaner — HRIS import, Placement Engine",
        "unit_amount": 12900,  # $129
        "env": "STRIPE_PRICE_CLEANER",
    },
    {
        "key": "equity",
        "name": "TRA Equity + Merit",
        "description": "Dual-lens equity, flight risk, merit pool remediation",
        "unit_amount": 24900,  # $249
        "env": "STRIPE_PRICE_EQUITY",
    },
    {
        "key": "tracker",
        "name": "TRA Candidate Tracker",
        "description": "Recruiting pipeline and offer packages",
        "unit_amount": 12900,
        "env": "STRIPE_PRICE_TRACKER",
    },
    {
        "key": "closer",
        "name": "TRA Closer",
        "description": "Four-year total wealth projection + PDF",
        "unit_amount": 19900,
        "env": "STRIPE_PRICE_CLOSER",
    },
    {
        "key": "suite",
        "name": "TRA Full Suite",
        "description": "All modules: Cleaner, Equity + Merit, Tracker, Closer",
        "unit_amount": 49900,  # $499
        "env": "STRIPE_PRICE_SUITE",
    },
]


def main() -> None:
    key = os.environ.get("STRIPE_SECRET_KEY", "").strip()
    if not key:
        print("Set STRIPE_SECRET_KEY first (test or live secret key).")
        sys.exit(1)
    stripe.api_key = key
    mode = "LIVE" if key.startswith("sk_live") else "TEST"
    print(f"Creating products in Stripe ({mode})…")

    lines = [
        f"# Generated by setup-stripe-products.py ({mode})",
        f"STRIPE_SECRET_KEY={key}",
        "PUBLIC_WEB_URL=https://totalrewardsaccelerator.com",
        "# After Dashboard → Developers → Webhooks → add endpoint:",
        "#   https://tra-api-starter.onrender.com/api/v1/billing/webhook",
        "# events: checkout.session.completed, customer.subscription.updated,",
        "#         customer.subscription.deleted, customer.subscription.paused",
        "# STRIPE_WEBHOOK_SECRET=whsec_...",
        "",
    ]

    for p in PRODUCTS:
        product = stripe.Product.create(
            name=p["name"],
            description=p["description"],
            metadata={"tra_product": p["key"]},
        )
        price = stripe.Price.create(
            product=product["id"],
            unit_amount=p["unit_amount"],
            currency="usd",
            recurring={"interval": "month"},
            metadata={"tra_product": p["key"]},
        )
        dollars = p["unit_amount"] / 100
        print(f"  {p['key']}: product={product['id']} price={price['id']} (${dollars:.0f}/mo)")
        lines.append(f"{p['env']}={price['id']}")

    root = Path(__file__).resolve().parents[1]
    out = root / "api" / ".env.stripe"
    out.write_text("\n".join(lines) + "\n")
    out.chmod(0o600)

    desktop = Path.home() / "Desktop" / "TRA_Stripe_Setup"
    desktop.mkdir(exist_ok=True)
    desk_out = desktop / "stripe-env-for-render.txt"
    desk_out.write_text(
        out.read_text()
        + "\n\n# Also set on Render tra-api-starter Environment, then Manual Deploy.\n"
        + "# SYSTEM_ADMIN_EMAILS=mikez.lopez15@gmail.com\n"
    )
    desk_out.chmod(0o600)
    print(f"\nWrote {out}")
    print(f"Wrote {desk_out}")
    print("\nNext:")
    print("  1) Create webhook in Stripe Dashboard (URL in file comments)")
    print("  2) Paste STRIPE_WEBHOOK_SECRET into the file")
    print("  3) Add all keys to Render tra-api-starter → Environment → Deploy")


if __name__ == "__main__":
    main()
